# More info on config here: https://golangci-lint.run/usage/configuration/
version: "2"
run:
  issues-exit-code: 1
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dupword
    - durationcheck
    - errorlint
    - exhaustruct
    - gocritic
    - nolintlint
    - predeclared
    - unparam
  settings:
    dupword:
      # only enable a few common cases here. Typically, duplicated words will be short
      keywords: ["a", "and", "at", "for", "from", "the"]
    exhaustruct:
      exclude:
        - ^crypto/tls\.Config$
        - ^net/http\.(Client|Server)
        - ^net\.(Dialer|TCPAddr)$
        - ^archive/tar\.Header$
        - ^k8s\.io/api/core/v1\.\w+$
        - ^k8s\.io/apimachinery/pkg/api/resource\.Quantity$
        - ^k8s\.io/apimachinery/pkg/apis/meta/v1\.(Create|Get|List|Watch|Patch|Update|Delete)Options$
        - ^k8s\.io/apimachinery/pkg/apis/meta/v1\.(Condition|LabelSelector|ObjectMeta)$
        - ^k8s\.io/client-go/tools/leaderelection/resourcelock\.ResourceLockConfig$
        - ^k8s\.io/client-go/tools/leaderelection\.(LeaderCallbacks|LeaderElectionConfig)$
        - ^sigs\.k8s\.io/controller-runtime/pkg/client\.Options$
        - ^sigs\.k8s\.io/controller-runtime/pkg/controller\.Options$
        - ^sigs\.k8s\.io/controller-runtime/pkg/controller\.TypedOptions$
        - ^sigs\.k8s\.io/controller-runtime/pkg/envtest\.(Environment|WebhookInstallOptions)$
        - ^sigs\.k8s\.io/controller-runtime/pkg/manager\.Options$
        - ^sigs\.k8s\.io/controller-runtime/pkg/metrics/server\.Options
        - ^sigs\.k8s\.io/controller-runtime/pkg/reconcile\.Result$
        - ^sigs\.k8s\.io/controller-runtime/pkg/scheme\.Builder$
        - ^sigs\.k8s\.io/controller-runtime/pkg/webhook\.Options
        - ^github\.com/containerd/cgroups/v3/cgroup2\.(CPU|Resources)
        - ^github\.com/docker/docker/api/types/container\.Config$
        - ^github\.com/docker/docker/api/types\.\w+Options$
        - ^github\.com/opencontainers/runtime-spec/specs-go\.\w+$ # Exempt the entire package. Too many big structs.
        - ^github\.com/prometheus/client_golang/prometheus(/.*)?\.\w+Opts$
        - ^github\.com/tychoish/fun/pubsub\.BrokerOptions$
        - ^github\.com/vishvananda/netlink\.\w+$ # Exempt the entire package. Too many big structs.
        - ^github\.com/neondatabase/autoscaling/neonvm/apis/neonvm/v1\.VirtualMachine(Migration)?(Spec)?$
        - ^github\.com/neondatabase/autoscaling/neonvm/apis/neonvm/v1\.IPPool$
        - ^github\.com/neondatabase/autoscaling/pkg/agent/core\.ActionSet$
        - ^github\.com/neondatabase/autoscaling/pkg/util/patch\.Operation$
        - ^github\.com/neondatabase/autoscaling/pkg/util/watch\.HandlerFuncs$
        - ^github\.com/cert-manager/cert-manager/pkg/apis/certmanager/v1\.Certificate(Request)?(Spec)?$
    gocritic:
      enabled-checks:
        - commentedOutImport
      enabled-tags:
        - diagnostic
      disabled-tags:
        - style
        - performance
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$ # ChanMutex contains only a channel, which *is* safe to copy
        text: 'copylocks: .* copies lock value.*: github\.com/neondatabase/autoscaling/pkg/util\.ChanMutex'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - Prefix(k8s.io)
        - Prefix(github.com/neondatabase/autoscaling)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
