# More info on config here: https://golangci-lint.run/usage/configuration/
run:
  deadline: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  govet:
    check-shadowing: true

linters:
  enable:
    - goimports
    - dupword
    - bodyclose
    - nolintlint
    - asciicheck
    - errchkjson
    - durationcheck
    - exportloopref
    - errname
    - errorlint
    # - gci # deterministic/consistent import order
    - noctx
