apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-view
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-view
rules:
- apiGroups: ["vm.neon.tech"]
  resources: ["virtualmachines"]
  verbs: ["get", "list", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-vm-view
roleRef:
  kind: ClusterRole
  name: vm-view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-agent-config
  namespace: kube-system
data:
  config.json: '{
    "scaling": {
      "requestTimeoutSeconds": 10
    },
    "informant": {
      "serverPort": 10301,
      "retryServerMinWaitSeconds": 5,
      "retryServerNormalWaitSeconds": 5,
      "registerRetrySeconds": 5,
      "requestTimeoutSeconds": 1,
      "registerTimeoutSeconds": 2,
      "downscaleTimeoutSeconds": 2
    },
    "metrics": {
      "loadMetricPrefix": "host_",
      "requestTimeoutSeconds": 2,
      "secondsBetweenRequests": 5
    },
    "scheduler": {
      "schedulerName": "autoscale-scheduler",
      "requestTimeoutSeconds": 2,
      "requestPort": 10299
    },
    "billing": {
      "url": "http://neon-internal-api.aws.neon.build/billing/api/v1",
      "cpuMetricName": "effective_compute_seconds",
      "collectEverySeconds": 5,
      "pushEverySeconds": 30,
      "pushTimeoutSeconds": 2
    }
  }'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: autoscaler-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: autoscaler-agent
  template:
    metadata:
      labels:
        name: autoscaler-agent
    spec:
      serviceAccountName: autoscaler-agent
      containers:
        - name: autoscaler-agent
          # hey! This image name is hard-coded in .github/workflows/release.yaml - make sure to
          # update that as well if you change this line!
          image: neondatabase/autoscaler-agent:v0.1.12
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONFIG_PATH
            value: /etc/autoscaler-agent-config/config.json
          volumeMounts:
          - name: config
            mountPath: /etc/autoscaler-agent-config
      volumes:
      - name: config
        configMap:
          name: autoscaler-agent-config
