FROM debian:11 AS build-deps

RUN apt-get update && apt-get -y install \
    make \
    curl

FROM build-deps AS build

ADD . /src
RUN cd /src && make kernel

FROM alpine:3.16
COPY --from=build /src/neonvm/hack/vmlinuz /vmlinuz
RUN chmod 777 /vmlinuz
