---
apiVersion: vm.neon.tech/v1
kind: VirtualMachine
metadata:
  name: postgres14-disk-test
  annotations:
    # In this example, these bounds aren't necessary. So... here's what they look like :)
    autoscaling.neon.tech/bounds: '{ "min": { "cpu": 0.25, "mem": "1Gi" }, "max": { "cpu": 4, "mem": "4Gi" } }'
  labels:
    autoscaling.neon.tech/enabled: "true"
    # Uncomment the line below to continuously migrate the VM (TESTING ONLY)
    # autoscaler/testing-only-always-migrate: ""
spec:
  schedulerName: autoscale-scheduler
  guest:
    cpus: { min: 0.25, use: 0.25, max: 1.5 }
    memorySlotSize: 1Gi
    memorySlots: { min: 1, use: 1, max: 4 }
    rootDisk:
      image: pg14-disk-test:dev
      size: 8Gi
    ports:
      - port: 22   # ssh
      - port: 5432 # postgres
      - port: 9100 # metrics
      - port: 10301 # informant
