---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vxlan-controller
  namespace: system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vxlan-controller
rules:
- apiGroups:
  - ""
  resources: ["nodes"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vxlan-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vxlan-controller
subjects:
- kind: ServiceAccount
  name: vxlan-controller
  namespace: system
