apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-virtualmachine-editor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neonvm-virtualmachine-editor-role
subjects:
- kind: ServiceAccount
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: v1
data:
  config.json: "{\n  \"scaling\": {\n    \"requestTimeoutSeconds\": 10,\n    \"retryFailedRequestSeconds\"\
    : 5,\n    \"defaultConfig\": {\n      \"loadAverageFractionTarget\": 0.9,\n  \
    \    \"memoryUsageFractionTarget\": 0.75\n    }\n  },\n  \"monitor\": {\n    \"\
    serverPort\": 10301,\n    \"responseTimeoutSeconds\": 5,\n    \"connectionTimeoutSeconds\"\
    : 4,\n    \"connectionRetryMinWaitSeconds\": 5,\n    \"unhealthyAfterSilenceDurationSeconds\"\
    : 20,\n    \"unhealthyStartupGracePeriodSeconds\": 20,\n    \"maxHealthCheckSequentialFailuresSeconds\"\
    : 30,\n    \"retryDeniedDownscaleSeconds\": 5,\n    \"deniedDownscaleFollowUpWaitSeconds\"\
    : 1,\n    \"requestedUpscaleValidSeconds\": 10,\n    \"retryFailedRequestSeconds\"\
    : 3\n  },\n  \"metrics\": {\n    \"port\": 9100,\n    \"loadMetricPrefix\": \"\
    host_\",\n    \"requestTimeoutSeconds\": 2,\n    \"secondsBetweenRequests\": 5\n\
    \  },\n  \"scheduler\": {\n    \"schedulerName\": \"autoscale-scheduler\",\n \
    \   \"requestTimeoutSeconds\": 2,\n    \"requestAtLeastEverySeconds\": 5,\n  \
    \  \"retryFailedRequestSeconds\": 3,\n    \"retryDeniedUpscaleSeconds\": 2,\n\
    \    \"requestPort\": 10299\n  },\n  \"dumpState\": {\n    \"port\": 10300,\n\
    \    \"timeoutSeconds\": 5\n  },\n  \"billing\": {\n    \"url\": \"http://neon-vector.neon-control-plane.svc.cluster.local:8082/v1\"\
    ,\n    \"cpuMetricName\": \"effective_compute_seconds\",\n    \"activeTimeMetricName\"\
    : \"active_time_seconds\",\n    \"collectEverySeconds\": 4,\n    \"accumulateEverySeconds\"\
    : 24,\n    \"pushEverySeconds\": 30,\n    \"pushRequestTimeoutSeconds\": 30,\n\
    \    \"maxBatchSize\": 200\n  }\n}"
kind: ConfigMap
metadata:
  name: autoscaler-agent-config
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: autoscaler-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: autoscaler-agent
  template:
    metadata:
      labels:
        name: autoscaler-agent
    spec:
      containers:
      - env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CONFIG_PATH
          value: /etc/autoscaler-agent-config/config.json
        image: neondatabase/autoscaler-agent:v0.19.1
        name: autoscaler-agent
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        - containerPort: 9101
          name: vm-metrics
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 600Mi
          requests:
            cpu: 1000m
            memory: 600Mi
        volumeMounts:
        - mountPath: /etc/autoscaler-agent-config
          name: config
      serviceAccountName: autoscaler-agent
      volumes:
      - configMap:
          name: autoscaler-agent-config
        name: config
