[package]
name = "many-small-files"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4"
rand = "0.8"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
