apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipam-demo
  namespace: default
spec:
  config: '{
    "ipam": {
      "range":        "10.100.0.0/24",
      "range_start":  "10.100.0.100",
      "range_end":    "10.100.0.200",
      "network_name": "ipam-demo"
    }
  }'
