apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-view
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-virtualmachine-editor
roleRef:
  kind: ClusterRole
  name: neonvm-virtualmachine-editor-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-agent-config
  namespace: kube-system
data:
  config.json: '{
    "scaling": {
      "requestTimeoutSeconds": 10,
      "defaultConfig": {
        "loadAverageFractionTarget": 0.9
      }
    },
    "informant": {
      "serverPort": 10301,
      "retryServerMinWaitSeconds": 5,
      "retryServerNormalWaitSeconds": 5,
      "registerRetrySeconds": 5,
      "requestTimeoutSeconds": 1,
      "registerTimeoutSeconds": 2,
      "downscaleTimeoutSeconds": 2,
      "unhealthyAfterSilenceDurationSeconds": 20,
      "unhealthyStartupGracePeriodSeconds": 20
    },
    "metrics": {
      "loadMetricPrefix": "host_",
      "requestTimeoutSeconds": 2,
      "secondsBetweenRequests": 5
    },
    "scheduler": {
      "schedulerName": "autoscale-scheduler",
      "requestTimeoutSeconds": 2,
      "requestPort": 10299
    },
    "dumpState": {
      "port": 10300,
      "timeoutSeconds": 5
    }
  }'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: autoscaler-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: autoscaler-agent
  template:
    metadata:
      labels:
        name: autoscaler-agent
    spec:
      serviceAccountName: autoscaler-agent
      containers:
        - name: autoscaler-agent
          image: autoscaler-agent:dev
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONFIG_PATH
            value: /etc/autoscaler-agent-config/config.json
          volumeMounts:
          - name: config
            mountPath: /etc/autoscaler-agent-config
      volumes:
      - name: config
        configMap:
          name: autoscaler-agent-config
