FROM debian:11 AS build-deps

ARG KERNEL_VERSION

RUN set -e \
    && echo "Build linux  kernel ${KERNEL_VERSION}" \
    && test -n "${KERNEL_VERSION}"

WORKDIR /build

RUN apt-get update && apt-get -y install \
    curl \
    ca-certificates \
    git \
    build-essential \
    flex \
    bison \
    libelf-dev \
    bc \
    libssl-dev \
    python3 \
    cpio \
    zstd \
    libncurses-dev \
    dwarves \
    rsync \
    kmod

RUN set -e \
    && mkdir linux \
    && curl -sfL https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${KERNEL_VERSION}.tar.xz -o linux-${KERNEL_VERSION} \
    && tar --strip-components=1 -C linux -xf linux-${KERNEL_VERSION}

FROM build-deps AS build

ADD linux-config-${KERNEL_VERSION} linux/.config

RUN cd linux && make -j `nproc`

RUN mkdir install && cd linux && make install INSTALL_DIR=../install
RUN mkdir modules_install && cd linux && make modules_install INSTALL_MOD_PATH=../modules_install
RUN cd linux && make bindeb-pkg

# Use alpine so that `cp` is available when loading custom kernels for the runner pod.
# See the neonvm controller's pod creation logic for more detail.
FROM alpine:3.16
COPY --from=build /build/linux/arch/x86/boot/bzImage /vmlinuz
COPY --from=build /build/install /
COPY --from=build /build/install_mod /
COPY --from=build /build/*.deb /
