#!/bin/sh

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

mount -t proc proc /proc
mount -t sysfs sysfs /sys
ln -s /proc/self/fd /dev/fd

ip link set up dev lo
ip link set up dev eth1
#ip address add 10.1.1.42/24 dev eth0
#ip route add default via 10.1.1.1 dev eth0
dhclient eth1; echo
ip a; ip r s
echo 'nameserver 8.8.8.8' > /etc/resolv.conf
echo '127.0.0.1 localhost.localdomain localhost' > /etc/hosts

# some postgres stuff

export POSTGRES_USER=postgres
export POSTGRES_PASSWORD=postgres
export POSTGRES_HOST_AUTH_METHOD=trust
export LANG=en_US.utf8
export PGDATA=/var/lib/postgresql/data

echo "start postgresql in background"
/usr/local/bin/docker-entrypoint.sh postgres -c 'config_file=/etc/postgresql/postgresql.conf' &
while ! su-exec postgres pg_isready; do sleep 1; done

echo; cat /etc/os-release | grep PRETTY_NAME | cut -d'"' -f2
echo; pg_config | grep VERSION | cut -d'=' -f2

echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"

echo "run console"
/sbin/getty -n -l /bin/sh 115200 /dev/console

echo "stopping postgresql"
su-exec postgres pg_ctl stop

echo "Powering off."
poweroff -f
