apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service_account.yaml
- role_binding.yaml
- config_map.yaml
- daemonset.yaml

images:
- name: autoscaler-agent
  newName: autoscaler-agent
  newTag: dev
