apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../multus-common

images:
- name: kube-multus
  newName: ghcr.io/k8snetworkplumbingwg/multus-cni
  newTag: v4.1.3-thick
  
resources:
- config_map.yaml
patchesStrategicMerge:
- cluster_role.yaml
- daemonset_patch.yaml

patches:
- target:
    kind: DaemonSet
    name: kube-multus-ds
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/command
      value: ["/usr/src/multus-cni/bin/multus-daemon"]
    - op: replace
      path: /spec/template/spec/containers/0/args
      value: []
