apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: overlay-for-pods
  namespace: system
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "overlay-for-pods",
    "type": "bridge",
    "bridge": "neon-br0",
    "ipam": {
      "type": "whereabouts",
      "range": "10.100.0.0/16",
      "range_start": "10.100.1.0",
      "range_end": "10.100.127.255"
    }
  }'
