apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscale-scheduler-virtualmachine-editor
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: autoscale-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: neonvm-virtualmachine-editor-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscale-scheduler-virtualmachinemigration-editor
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: autoscale-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: neonvm-virtualmachinemigration-editor-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscale-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: autoscale-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscale-scheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: autoscale-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoscale-scheduler-apiserver-auth-config
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: autoscale-scheduler
  namespace: kube-system
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apiserver-authentication-reader
