apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../multus-common

images:
- name: multus-cni
  newName: docker.io/bitnami/multus-cni
  newTag: 3.9.3

patchesStrategicMerge:
- daemonset_patch.yaml

patches:
- target:
    kind: DaemonSet
    name: kube-multus-ds
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/command
      value: ["/usr/src/multus-cni/bin/multus-daemon"]
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
        - "-cni-version=0.3.1"
        - "-cni-config-dir=/host/etc/cni/net.d"
        - "-multus-autoconfig-dir=/host/etc/cni/net.d"
        - "-multus-log-to-stderr=true"
        - "-multus-log-level=verbose"
    - op: replace
      path: /spec/template/spec/containers/0/securityContext/runAsNonRoot
      value: false
    - op: replace
      path: /spec/template/spec/containers/0/securityContext/runAsUser
      value: 0
