#!/usr/bin/env bash
#
# Helper script to clean up files autogenerated VM-related files.

# Allow this script to be run from outside the vm_image directory
cd -P -- "$(dirname -- "$0")"

rm -f ssh_id_rsa
rm -f ssh_id_rsa.pub
rm -f neonvm-builder
