apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscale-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: autoscale-scheduler
        plugins:
          multiPoint:
            enabled:
              - name: AutoscaleEnforcer
---
# TODO: put this in the KubeSchedulerConfiguration's plugin config, rather than a separate configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-plugin-config
  namespace: kube-system
data:
  autoscale-enforcer-config.json: |
    {
      "memBlockSize": "1Gi",
      "nodeDefaults": {
        "cpu": { "watermark": 0.9 },
        "memory": { "watermark": 0.9 },
        "computeUnit": { "vCPUs": 0.25, "mem": 1 },
        "minUsageScore": 0.5,
        "maxUsageScore": 0,
        "scorePeak": 0.8
      },
      "nodeOverrides": [],
      "schedulerName": "autoscale-scheduler",
      "dumpState": {
        "port": 10298,
        "timeoutSeconds": 5
      },
      "migrationDeletionRetrySeconds": 5,
      "doMigration": false,
      "randomizeScores": true
    }
