apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-scheduler # unstable name
  namespace: kube-system
  labels:
    component: scheduler
    tier: control-plane
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        name: autoscale-scheduler # stable name
        tier: control-plane
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: autoscale-scheduler
      containers:
      - image: autoscale-scheduler:dev
        command: ["/usr/bin/kube-scheduler", "--config=/etc/kubernetes/autoscale-scheduler-config/scheduler-config.yaml"]
        ports:
        - name: metrics
          containerPort: 9100
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: autoscale-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts:
          - name: scheduler-config-volume
            mountPath: /etc/kubernetes/autoscale-scheduler-config
          - name: plugin-config-volume
            mountPath: /etc/scheduler-plugin-config
      hostNetwork: false
      hostPID: false
      volumes:
        - name: scheduler-config-volume
          configMap:
            name: autoscale-scheduler-config
        - name: plugin-config-volume
          configMap:
            name: scheduler-plugin-config
