apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service_account.yaml
- role_binding.yaml
- config_map.yaml
- deployment.yaml

images:
- name: autoscale-scheduler
  newName: autoscale-scheduler
  newTag: dev
