# permissions for end users to edit virtualmachinemigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualmachinemigration-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/part-of: neonvm
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: virtualmachinemigration-editor-role
rules:
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachinemigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachinemigrations/status
  verbs:
  - get
