apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-view
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: autoscaler-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-virtualmachine-editor
roleRef:
  kind: ClusterRole
  name: neonvm-virtualmachine-editor-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: autoscaler-agent
  namespace: kube-system
