#!/bin/sh

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# system mounts
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
ln -s /proc/self/fd /dev/fd

# networking
ip link set up dev lo
ip link set up dev eth0
ip link set up dev eth1
dhclient eth0; echo
dhclient eth1; echo
ip address show
ip route show

echo; lsb_release -irc
echo "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"

echo "Start getty for console"
while true; do setsid -w /sbin/agetty -a root --keep-baud -p 115200,38400,9600 hvc0; sleep 1; done
# getty in background
#setsid bash -c 'while true; do setsid -w /sbin/agetty -a root --keep-baud -p 115200,38400,9600 hvc0; sleep 1; done'

echo "Exiting and shuting down vm"
poweroff -f
