#!/bin/bash

CLUSTER=lm-lab

###################

kubectl config unset current-context
kubectl config unset clusters.$CLUSTER
kubectl config unset users.$CLUSTER
kubectl config unset contexts.$CLUSTER
