name: Load base image tags and SHAs into env
description: Read versions.env for the current arch into $GITHUB_ENV
inputs:
  arch:
    description: Architecture, 'amd64' or 'arm64'
    required: true

runs:
  using: "composite"
  steps:
    - name: Load base image tags and SHAs into env
      shell: bash -euxo pipefail {0}
      env:
        INPUT_ARCH: ${{ inputs.arch }}
      run: |
        case "$INPUT_ARCH" in
            'amd64' )
                arch=AMD64
                ;;
            'arm64' )
                arch=ARM64
                ;;
            *)
                echo "Unexpected architecture $INPUT_ARCH"
                exit 1
                ;;
        esac
        
        grep -v '^#' versions.env | grep -E "^[A-Z_]+(_TAG|_SHA_$arch)=" | sed -e "s/_$arch=/=/g" >> $GITHUB_ENV
