apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- base.yaml

images:
- name: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/multus-cni
  newName: public.ecr.aws/eks/multus-cni

