apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/multus/v3.9.2-eksbuild.1/aws-k8s-multus.yaml

images:
- name: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/multus-cni
  newName: public.ecr.aws/eks/multus-cni

