name: Report Workflow Stats

on:
  workflow_run:
    workflows:
    - Handle `approved-for-ci-run` label
    - PR format verification
    - build-images
    - build-test-vm
    - check-cluster-autoscaler-builds
    - e2e-test
    - lints
    - release
    - test
    - vm-example
    - vm-kernel
    types: [completed]

jobs:
  gh-workflow-stats:
    name: Github Workflow Stats
    runs-on: ubuntu-22.04
    permissions:
      actions: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Export GH Workflow Stats
        uses: neondatabase/gh-workflow-stats-action@v0.1.4
        with:
          DB_URI: ${{ secrets.GH_REPORT_STATS_DB_RW_CONNSTR }}
          DB_TABLE: 'gh_workflow_stats_autoscaling'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_RUN_ID: ${{ github.event.workflow_run.id }}
