name: vm-example

on:
  schedule:
    - cron:  '42 4 * * 2'  # run once a week
  pull_request:
    paths:
      - ".github/workflows/vm-example.yaml"
  workflow_dispatch: # adds ability to run this manually

env:
  TARGET_ARCH: amd64

permissions:
  contents: read

jobs:
  vm-example:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: git checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: install golang
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: 'go.mod'
        timeout-minutes: 10

      - name: build daemon
        run:  make docker-build-daemon

      - name: build vm-builder
        run:  make bin/vm-builder

      - name: docker - setup buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - name: login to docker hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}

      - name: build vm-alpine:3.16
        run:  bin/vm-builder -src alpine:3.16 -dst neondatabase/vm-alpine:3.16 -target-arch linux/${TARGET_ARCH}
      - name: push vm-alpine:3.16
        run:  docker push -q neondatabase/vm-alpine:3.16

      - name: build vm-ubuntu:22.04
        run:  bin/vm-builder -src ubuntu:22.04 -dst neondatabase/vm-ubuntu:22.04 -target-arch linux/${TARGET_ARCH}
      - name: push  vm-ubuntu:22.04
        run:  docker push -q neondatabase/vm-ubuntu:22.04

      - name: build vm-debian:11
        run:  bin/vm-builder -src debian:11 -dst neondatabase/vm-debian:11 -target-arch linux/${TARGET_ARCH}
      - name: push  vm-debian:11
        run:  docker push -q neondatabase/vm-debian:11

      - name: build vm-postgres:14-alpine
        run:  bin/vm-builder -src postgres:14-alpine -dst neondatabase/vm-postgres:14-alpine -target-arch linux/${TARGET_ARCH}
      - name: push vm-postgres:14-alpine
        run:  docker push -q neondatabase/vm-postgres:14-alpine

      - name: build vm-postgres:15-alpine
        run:  bin/vm-builder -src postgres:15-alpine -dst neondatabase/vm-postgres:15-alpine -target-arch linux/${TARGET_ARCH}
      - name: push vm-postgres:15-alpine
        run:  docker push -q neondatabase/vm-postgres:15-alpine
